version: '3'

services:
  reading-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reading-agent
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./config.yaml:/app/config.yaml
    env_file: .env
    restart: unless-stopped 